### ISSUE TITLE
UserInfo data class  중복 존재

### ISSUE THREAD

**Issue by KeunyoungSong** [NBC-Phone-Project/SPN-application#32]
## 어떤 버그인가요?

UserInfo 데이터 클래스가 중복으로 선언되어 있습니다
사용하지 않는 데이터 자료형을 제거해야 합니다

## 참고할만한 자료(선택)

<img width="496" alt="image" src="https://github.com/NBC-Phone-Project/SPN-application/assets/84883277/1757d69e-0c98-4440-bef6-a0a4857401a4">

**Comment by YYG609** [comment]
#33 
해당 이슈 관해서
UserItems 삭제 후 커밋 했습니다
