### ISSUE TITLE
design: contact-layout

### ISSUE THREAD

**Issue by YYG609** [NBC-Phone-Project/SPN-application#6]
## 어떤 기능인가요?

contact-layout
- 프래그먼트, 리사이클러 뷰, 아이템 타이틀 추가

## 작업 세부 내용

- contact-layout에 사용 될 프래그먼트, 리사이클러 뷰, 아이템 타이틀 레이아웃 추가
- 기능 구현은 차 후 추가 예정

## 참고할만한 자료(선택)
![1](https://github.com/NBC-Phone-Project/SPN-application/assets/151480860/10efd985-a82f-4d61-9725-5d7a6a619baa)

**Comment by KeunyoungSong** [comment]
LGTM
