### ISSUE TITLE
feat: contact dummy data

### ISSUE THREAD

**Issue by YYG609** [NBC-Phone-Project/SPN-application#9]
## 어떤 기능인가요?

ContactFragment에 들어갈 더미데이터 추가와 UserAdapter 추가

## 작업 세부 내용

ContactFragment에서 사용되는 더미데이터와 이를 활용하는 UserAdapter 추가

**Comment by KeunyoungSong** [comment]
이후에 data class 속성 들어갈 내용 회의 후에 관련 기능 개발하겠습니다
